# Run this script to add all the essential packages.
# use "Pkg.instantialize()" to load them and add them to Project.toml
# Pkg.activate(".") activates the Project.toml

import Pkg

Pkg.add("Parameters")
Pkg.add("Unitful")
Pkg.add("BibTeX")
Pkg.add("StaticArrays")
Pkg.add("LinearAlgebra")
Pkg.add("ForwardDiff")
Pkg.add("MuladdMacro")
Pkg.add("InternedStrings")
Pkg.add("Setfield")
Pkg.add("UnPack")
Pkg.add("LaTeXStrings")
Pkg.add("Static")
Pkg.add("Interpolations")
Pkg.add("SpecialFunctions")
Pkg.add("Roots")
Pkg.add("Loess")
Pkg.add("StatsBase")
Pkg.add("KernelDensitySJ")
Pkg.add("Unidecode")
Pkg.add("WriteVTK")
Pkg.add("Colors")
Pkg.add("MeshIO")
Pkg.add("FileIO")
Pkg.add("Geodesy")
Pkg.add("LightXML")
Pkg.add("NearestNeighbors")
Pkg.add("Glob")
Pkg.add("GeometryBasics")
Pkg.add("JLD2")
Pkg.add("NCDatasets")
Pkg.add("ParallelStencil")
Pkg.add("NetCDF")
# Pkg.add("CairoMakie")
Pkg.add("GeoParams")
Pkg.add("GeophysicalModelGenerator")
Pkg.add("JustPIC")
Pkg.add("JustRelax")
Pkg.add("ParallelStencil")